### ISSUE TITLE
update the description

### ISSUE THREAD

**Issue by Haroenv** [osoc16/website#5]
right now the description still shows "2015".

**Comment by Dobbelsteen** [comment]
All references should now be correct, if I missed any, please point out where :)

**Comment by Haroenv** [comment]
In the description on github it still says 

> Website for open Summer of code 2015

**Comment by Dobbelsteen** [comment]
Ok, fixed now, didn't know what you were referring to at first

**Comment by Haroenv** [comment]
super :smile:
